# Generated by Django 3.2.7 on 2021-11-30 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211129_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
